---
- name: copy config
  copy:
    src: files
    dest: "/home/{{ user.name }}/ansible-xconf"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: set config
  command: "sh run.sh chdir=/home/{{ user.name }}/ansible-xconf/files"
  become: true
  become_user: "{{ user.name }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1001/bus

