---
- name: Install base packags
  pacman:
    name: "{{ base_packages }}"
    state: present

- name: Create AUR Directory
  file: path=/home/{{ user.name }}/{{ aur.dir }}
        state=directory
        owner={{ user.name }}
        group={{ user.group }}

- name: Install AUR base packages
  aur:
    name: "{{ aur.packages }}"
    user: "{{ user.name }}"
